### ISSUE TITLE
 content-type:diagram reports error

### ISSUE THREAD

**Issue by Always-Starter** [contentstack/contentstack-cli-content-type#2]
Command: `csdx content-type:diagram -s "stackID" -o "contentstack/content-model.svg"
`
It reports error:
```
Requesting data... !
    ContentstackError: Bad Request
```

<img width="976" alt="image" src="https://user-images.githubusercontent.com/7390027/180413318-dbfabf15-cfa9-453e-8ac1-c51a555b495d.png">

**Comment by AniketDev7** [comment]
Hi @Always-Starter   We tried the same command which u shared and were unable to replicate this at our end.
We used latest contentstack-cli-content-type version of 1.1.1 
![image](https://github.com/Contentstack-Solutions/contentstack-cli-content-type/assets/62753263/587182b7-aaff-445f-ae18-fc68368ea3c4)

Can you share which CLI and content type plugin version did u tried and does the stack you tried had branches enabled ?

cc: @netrajpatel  @cs-raj

**Comment by cs-raj** [comment]
Closing this issue as there was no further communication 
cc: @netrajpatel @aman19K @AniketDev7 @shafeeqd959
